"""Export the FID record for the Renode firmware (C4).

Generates one FID record with fid.generate_record at a FIXED seed and
writes it as a C header (const float array) plus the truth values, so the
firmware runs the byte-identical estimator core on data the host scored.

Usage: python3 tools/export_fid_vector.py   (writes firmware/targets/stm32f4/)
"""
import hashlib
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "firmware" / "targets"

SEED = 4242
# Short record (8192 samples) so the estimator's static workspace fits the
# RP2040's 256 KB SRAM; compiled with -DFE_SEED_WINDOW=2048 the core's
# static buffers fit comfortably.
BASE = dict(v0=2e-6, fs=20_000.0, blanking_s=0.2, record_s=0.4096,
            r_coil=120.0, l_coil=2e-3, e_amp=7e-9, i_amp=0.05e-12,
            gain=5000.0, adc_bits=16, adc_fs=2.048)


def main():
    sys.path.insert(0, str(ROOT / "poc"))
    import fid

    rec = fid.generate_record(b_tesla=50e-6, tau=1.5, rng=SEED, phase=0.7,
                              sigma_in=1e-7, **BASE)
    v = rec["v_adc"].astype(np.float32)
    truth = rec["f_larmor"]
    OUT.mkdir(parents=True, exist_ok=True)
    with (OUT / "fid_vector.h").open("w") as f:
        f.write("/* Generated by tools/export_fid_vector.py -- DO NOT EDIT.\n"
                " * seed=%d, sha256=%.16s\n"
                " * truth f_larmor = %.6f Hz\n"
                " */\n" % (SEED,
                           hashlib.sha256(v.tobytes()).hexdigest(), truth))
        f.write("#define FID_N %d\n" % len(v))
        f.write("#define FID_FS %.1f\n" % rec["fs"])
        f.write("#define FID_T0 %.6f\n" % rec["blanking_s"])
        f.write("#define FID_TRUTH_HZ %.6f\n" % truth)
        f.write("static const float fid_record[FID_N] = {\n")
        for i in range(0, len(v), 4):
            f.write("  " + ", ".join("%.9e" % x for x in v[i:i+4]) + ",\n")
        f.write("};\n")
    print("wrote %s (%d samples, truth %.4f Hz)"
          % (OUT / "fid_vector.h", len(v), truth))


if __name__ == "__main__":
    main()
